### ISSUE TITLE
Change of Mapillary API

### ISSUE THREAD

**Issue by gyllen** [ubahnverleih/mapillary2JOSM#3]
Hi,

I had to change the geojson API to return valid geojson. See this issue https://github.com/mapillary/mapillary_issues/issues/53. I think that broke your tool. I think its pretty straight forward to fix. Sorry for the late notice though.

**Comment by gyllen** [comment]
Also let me know if there is anything I can do to help you update.

**Comment by ubahnverleih** [comment]
Thank you. fixed it.
(should be live on the server tomorrow)

**Comment by gyllen** [comment]
Awesome!
