### ISSUE TITLE
Mapillary geojson API for gpx, possibly use sequences search

### ISSUE THREAD

**Issue by gyllen** [ubahnverleih/mapillary2JOSM#6]
Is it possible to change the gpx conversion to use

```
https://api.mapillary.com/v1/s/search?min-lat=&max-lat&min-lon=&max-lon=&geojson=true
```

api instead of the slower im api used now. This will greatly improve gpx download performance. Let me know if you miss something in that output.

**Comment by ubahnverleih** [comment]
replaced it. I hope i get also all images in bounding box.

**Comment by baditaflorin** [comment]
Download fehlgeschlagen. Bereich zu groß.

What is the API limit for an area ? Or for number of pictures ?

i am trying to download the images that i have taken to use in josm, and i cannot even download an area that have around 40 photos

http://osm.lyrk.de/mapillary2JOSM/

I am planing to use mapillary for the openstreetmap mapping party but if we are not able to use the pictures that we will make doring the mapping party,it will be useless to use it...

Mapillary, can we do something to increase the API limit to something higher then 1000.

@ubahnverleih can you also access the contributors in the bounding box to see if that number is higher then the API limit ? Without sending a request that will be rejected

 <span ng-repeat="user in toplist" class="ng-scope">
    <div class="user-text">
      <div class="row1">
        <a ng-href="/#/profile/baditaflorin" class="ng-binding" href="/#/profile/baditaflorin">
          baditaflorin:
        </a>
      </div>
      <div class="row2 ng-binding">
        188
      </div>
    </div>
  </span>

**Comment by ubahnverleih** [comment]
new version is not live on the website now. maybe it works with the new API. will update it on the website in the next days.

**Comment by gyllen** [comment]
@ubahnverleih Very nice update, did you get better performance from the API

@baditaflorin Can you still not download your gpx?

**Comment by ubahnverleih** [comment]
@gyllen i've not exactly testet the performance but it feel faster. i will role out it on the webpage, when i fixed the combination of tile-layer and geojson.
@baditaflorin can you test if it work with the new API implementation (cloning this version from github)?

**Comment by baditaflorin** [comment]
I will test, until now under 1000 works. But the josm plug-in needs improvement, it`s a bottleneck and if i made photos in walk mode, it will open 20 photos when i click on only one photo. 

Do you have an idea what part of josm is the code that load the GPX file, so i can try and promote to the osm community to change the code and allow orientation arrows in josm, auto preview image and smarter zoom control, for a better and singleness use of the photos
