### ISSUE TITLE
Try out experimental tiles

### ISSUE THREAD

**Issue by gyllen** [ubahnverleih/mapillary2JOSM#7]
You can try our experimental sequence tiles if you want to be able to display all sequences

The address is
     http://{s}.tiles.mapillary.com/{z}/{x}/{y}

**Comment by ubahnverleih** [comment]
replaced the GeoJSON layer with TileLayer - but in lower zoom-levels not all data is shown

**Comment by gyllen** [comment]
Very cool, its still experimental, might still be some glicthes in tiles.

**Comment by ubahnverleih** [comment]
ok maybe i should use GeoJSON in higher Zoomlevels.

**Comment by gyllen** [comment]
For now that is what we are doing on the main page. If you can keep on showing both for a while I think that would be the best.

**Comment by gyllen** [comment]
Awesome work with this editor by the way!
